### ISSUE TITLE
Breaking terms of license

### ISSUE THREAD

**Issue by liamengland1** [superover/TikTok-Blocklist#1]
Hi,

It's obvious that you've copied some of my list and are violating the terms of the MIT License. Please add a link back to my repo and/or reproduce the license in order to comply.

thanks

**Comment by superover** [comment]
@llacb47 Hi,
Sorry about that. Just kept adding domains. Forgot all about the license thing.

**Comment by liamengland1** [comment]
Hi,

are you going to add the license or link back to my repo?

**Comment by liamengland1** [comment]
https://github.com/superover/TikTok-Blocklist/commit/a27028bddf8d5eb3b884807ea737b8835cffd812
